#!/usr/bin/python

import os
import sys

THIS_DIR = os.path.dirname(os.path.realpath(__file__))
PARENT_DIR = os.path.dirname(THIS_DIR)
sys.path.insert(0, PARENT_DIR)
import morph.cli

morph.cli.main()
