# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readability.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadabilityDialog(object):
    def setupUi(self, ReadabilityDialog):
        ReadabilityDialog.setObjectName("ReadabilityDialog")
        ReadabilityDialog.resize(898, 658)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReadabilityDialog.sizePolicy().hasHeightForWidth())
        ReadabilityDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReadabilityDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(ReadabilityDialog)
        self.frame.setMinimumSize(QtCore.QSize(730, 90))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.inputPathEdit = QtWidgets.QLineEdit(self.frame)
        self.inputPathEdit.setGeometry(QtCore.QRect(60, 30, 661, 20))
        self.inputPathEdit.setObjectName("inputPathEdit")
        self.targetSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.targetSpinBox.setGeometry(QtCore.QRect(660, 60, 61, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetSpinBox.sizePolicy().hasHeightForWidth())
        self.targetSpinBox.setSizePolicy(sizePolicy)
        self.targetSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.targetSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetSpinBox.setDecimals(1)
        self.targetSpinBox.setProperty("value", 98.0)
        self.targetSpinBox.setObjectName("targetSpinBox")
        self.targetLabel = QtWidgets.QLabel(self.frame)
        self.targetLabel.setGeometry(QtCore.QRect(595, 60, 61, 20))
        self.targetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetLabel.setObjectName("targetLabel")
        self.inputPathButton = QtWidgets.QPushButton(self.frame)
        self.inputPathButton.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.inputPathButton.setObjectName("inputPathButton")
        self.inputDirectoryLabel = QtWidgets.QLabel(self.frame)
        self.inputDirectoryLabel.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inputDirectoryLabel.setFont(font)
        self.inputDirectoryLabel.setObjectName("inputDirectoryLabel")
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(ReadabilityDialog)
        self.frame_2.setMinimumSize(QtCore.QSize(130, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.closeButton = QtWidgets.QPushButton(self.frame_2)
        self.closeButton.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.closeButton.setDefault(False)
        self.closeButton.setObjectName("closeButton")
        self.analyzeButton = QtWidgets.QPushButton(self.frame_2)
        self.analyzeButton.setGeometry(QtCore.QRect(10, 30, 91, 23))
        self.analyzeButton.setDefault(True)
        self.analyzeButton.setObjectName("analyzeButton")
        self.horizontalLayout_2.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generalSettingsGroupBox = QtWidgets.QGroupBox(ReadabilityDialog)
        self.generalSettingsGroupBox.setMinimumSize(QtCore.QSize(730, 180))
        self.generalSettingsGroupBox.setObjectName("generalSettingsGroupBox")
        self.masterFreqButton = QtWidgets.QPushButton(self.generalSettingsGroupBox)
        self.masterFreqButton.setGeometry(QtCore.QRect(10, 40, 41, 23))
        self.masterFreqButton.setObjectName("masterFreqButton")
        self.masterFreqLabel = QtWidgets.QLabel(self.generalSettingsGroupBox)
        self.masterFreqLabel.setGeometry(QtCore.QRect(60, 21, 106, 16))
        self.masterFreqLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.masterFreqLabel.setObjectName("masterFreqLabel")
        self.masterFreqEdit = QtWidgets.QLineEdit(self.generalSettingsGroupBox)
        self.masterFreqEdit.setGeometry(QtCore.QRect(60, 40, 661, 20))
        self.masterFreqEdit.setObjectName("masterFreqEdit")
        self.knownMorphsButton = QtWidgets.QPushButton(self.generalSettingsGroupBox)
        self.knownMorphsButton.setGeometry(QtCore.QRect(10, 90, 41, 23))
        self.knownMorphsButton.setObjectName("knownMorphsButton")
        self.knownMorphsLabel = QtWidgets.QLabel(self.generalSettingsGroupBox)
        self.knownMorphsLabel.setGeometry(QtCore.QRect(60, 70, 86, 16))
        self.knownMorphsLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.knownMorphsLabel.setObjectName("knownMorphsLabel")
        self.knownMorphsEdit = QtWidgets.QLineEdit(self.generalSettingsGroupBox)
        self.knownMorphsEdit.setGeometry(QtCore.QRect(60, 90, 661, 20))
        self.knownMorphsEdit.setObjectName("knownMorphsEdit")
        self.outputFreqLabel = QtWidgets.QLabel(self.generalSettingsGroupBox)
        self.outputFreqLabel.setGeometry(QtCore.QRect(60, 117, 113, 16))
        self.outputFreqLabel.setObjectName("outputFreqLabel")
        self.outputFrequencyButton = QtWidgets.QPushButton(self.generalSettingsGroupBox)
        self.outputFrequencyButton.setGeometry(QtCore.QRect(10, 140, 41, 23))
        self.outputFrequencyButton.setObjectName("outputFrequencyButton")
        self.outputFrequencyEdit = QtWidgets.QLineEdit(self.generalSettingsGroupBox)
        self.outputFrequencyEdit.setGeometry(QtCore.QRect(60, 140, 661, 20))
        self.outputFrequencyEdit.setObjectName("outputFrequencyEdit")
        self.horizontalLayout.addWidget(self.generalSettingsGroupBox)
        self.groupBox = QtWidgets.QGroupBox(ReadabilityDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox.setObjectName("groupBox")
        self.frequencyListCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.frequencyListCheckBox.setGeometry(QtCore.QRect(10, 130, 131, 17))
        self.frequencyListCheckBox.setChecked(True)
        self.frequencyListCheckBox.setObjectName("frequencyListCheckBox")
        self.wordReportCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.wordReportCheckBox.setGeometry(QtCore.QRect(10, 70, 131, 17))
        self.wordReportCheckBox.setChecked(True)
        self.wordReportCheckBox.setObjectName("wordReportCheckBox")
        self.studyPlanCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.studyPlanCheckBox.setGeometry(QtCore.QRect(10, 100, 131, 17))
        self.studyPlanCheckBox.setChecked(True)
        self.studyPlanCheckBox.setObjectName("studyPlanCheckBox")
        self.readabilityReportCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.readabilityReportCheckBox.setGeometry(QtCore.QRect(10, 40, 131, 17))
        self.readabilityReportCheckBox.setChecked(True)
        self.readabilityReportCheckBox.setObjectName("readabilityReportCheckBox")
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outputText = QtWidgets.QPlainTextEdit(ReadabilityDialog)
        self.outputText.setReadOnly(True)
        self.outputText.setObjectName("outputText")
        self.horizontalLayout_3.addWidget(self.outputText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ReadabilityDialog)
        QtCore.QMetaObject.connectSlotsByName(ReadabilityDialog)

    def retranslateUi(self, ReadabilityDialog):
        _translate = QtCore.QCoreApplication.translate
        ReadabilityDialog.setWindowTitle(_translate("ReadabilityDialog", "Morph Man Readability Analyzer"))
        self.targetLabel.setText(_translate("ReadabilityDialog", "Target %"))
        self.inputPathButton.setText(_translate("ReadabilityDialog", "..."))
        self.inputDirectoryLabel.setText(_translate("ReadabilityDialog", "Input Directory"))
        self.closeButton.setText(_translate("ReadabilityDialog", "Close"))
        self.analyzeButton.setText(_translate("ReadabilityDialog", "Analyze!"))
        self.generalSettingsGroupBox.setTitle(_translate("ReadabilityDialog", "General Settings"))
        self.masterFreqButton.setText(_translate("ReadabilityDialog", "..."))
        self.masterFreqLabel.setText(_translate("ReadabilityDialog", "Master Frequency List"))
        self.knownMorphsButton.setText(_translate("ReadabilityDialog", "..."))
        self.knownMorphsLabel.setText(_translate("ReadabilityDialog", "Known Morphs DB"))
        self.outputFreqLabel.setText(_translate("ReadabilityDialog", "Output Directory"))
        self.outputFrequencyButton.setText(_translate("ReadabilityDialog", "..."))
        self.groupBox.setTitle(_translate("ReadabilityDialog", "Outputs"))
        self.frequencyListCheckBox.setText(_translate("ReadabilityDialog", "Frequency List"))
        self.wordReportCheckBox.setText(_translate("ReadabilityDialog", "Word Report"))
        self.studyPlanCheckBox.setText(_translate("ReadabilityDialog", "Target Study Plan"))
        self.readabilityReportCheckBox.setText(_translate("ReadabilityDialog", "Readability Report"))
